name: Frontend CI/CD

on: 
  push:
    branches:
      - main
  
jobs:
  deploy:
    name: Deploy Frontend Infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          path: ''

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          role-to-assume: arn:aws:iam::193544298890:role/GithubActionRole
          aws-region: us-east-1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with: 
          node-version: "22.14.0"
      
      - name: Install dependencies
        working-directory: cr_frontend
        run: npm install

      - name: Build React App
        working-directory: cr_frontend
        run: npm run build

      - name: Deploy to S3 bucket
        run: aws s3 sync cr_frontend/dist/ s3://rsoon-resume.com --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3M8L6D1ISXELF --paths "/*"
